# Generated by Django 2.2.2 on 2019-06-09 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
