# Generated by Django 2.2.2 on 2019-06-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_jwt_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_secret',
        ),
    ]
